# Reddit data with actual posts and comments
REDDIT_DATA = {
    "avis": {
        "posts": [
            # r/travel
            {"id": "t1", "subreddit": "r/travel", "title": "Avis car rental question", "score": 12, "comments": 15, "sentiment": "neutral", "date": "2025-02-10T10:30:00Z",
             "top_comments": ["I'm planning a trip soon. What are the most important things to consider?", "Make sure to check their insurance policies!"]},
            {"id": "t2", "subreddit": "r/travel", "title": "Hertz Vs Avis car rental", "score": 7, "comments": 10, "sentiment": "negative", "date": "2025-02-09T14:20:00Z",
             "top_comments": ["I've had better experiences with Hertz in the past.", "Avis has some hidden fees that annoyed me."]},
            {"id": "t3", "subreddit": "r/travel", "title": "Avis Rental car from US drive to Canada", "score": 5, "comments": 8, "sentiment": "neutral", "date": "2025-02-08T09:15:00Z",
             "top_comments": ["Cross-border rentals can be tricky. Just be prepared for policies.", "Make sure you have the proper paperwork ready."]},
            {"id": "t4", "subreddit": "r/travel", "title": "Avis Car Rental Advisory", "score": 9, "comments": 12, "sentiment": "positive", "date": "2025-02-07T16:45:00Z",
             "top_comments": ["Great tips! I learned some lessons the hard way.", "Always check the car condition before you leave."]},
            {"id": "t5", "subreddit": "r/travel", "title": "Avis Car Rental", "score": 11, "comments": 6, "sentiment": "negative", "date": "2025-02-06T11:30:00Z",
             "top_comments": ["Their service varies by location, just a heads-up!", "Had a rough time with the customer service — be cautious."]},
            # r/TravelHacks
            {"id": "t6", "subreddit": "r/TravelHacks", "title": "First time car hire with Avis (USA - West Coast) - what pitfalls should I avoid?", "score": 15, "comments": 20, "sentiment": "neutral", "date": "2025-02-05T08:00:00Z",
             "top_comments": ["Ensure you read the contract carefully.", "Avoid renting from the airport if possible, it's cheaper elsewhere."]},
            {"id": "t7", "subreddit": "r/TravelHacks", "title": "AVIS reputation", "score": 25, "comments": 30, "sentiment": "negative", "date": "2025-02-04T13:20:00Z",
             "top_comments": ["I've had many bad experiences renting from them.", "Some locations are great, but others... not so much."]},
            {"id": "t8", "subreddit": "r/TravelHacks", "title": "Why is AVIS so bad as of recent? Any reputable car companies to change to?", "score": 10, "comments": 15, "sentiment": "negative", "date": "2025-02-03T10:10:00Z",
             "top_comments": ["Consider looking into Enterprise — I've heard good things.", "AVIS's customer service has really dipped lately."]},
            {"id": "t9", "subreddit": "r/TravelHacks", "title": "Avis Car Rental Early Return?", "score": 8, "comments": 10, "sentiment": "neutral", "date": "2025-02-02T15:30:00Z",
             "top_comments": ["You might face extra fees if you return early.", "Always clarify this before signing."]},
            {"id": "t10", "subreddit": "r/TravelHacks", "title": "Is Avis Mystery Car worth it?", "score": 6, "comments": 5, "sentiment": "neutral", "date": "2025-02-01T09:45:00Z",
             "top_comments": ["It depends on what you get — could be a bargain, or a disaster.", "I've known people who got great deals; others not so much."]},
            {"id": "t11", "subreddit": "r/TravelHacks", "title": "Avis/Budget claiming damage on a rental I returned 7 months ago.", "score": 11, "comments": 20, "sentiment": "negative", "date": "2025-01-31T14:00:00Z",
             "top_comments": ["Document everything you can!", "This happens way too often, be cautious."]},
            {"id": "t12", "subreddit": "r/TravelHacks", "title": "If you are under 25, DO NOT RENT WITH AVIS", "score": 18, "comments": 25, "sentiment": "negative", "date": "2025-01-30T11:20:00Z",
             "top_comments": ["They really do charge ridiculous fees for young renters.", "I wish I had listened to this advice!"]},
            # r/Scams
            {"id": "t13", "subreddit": "r/Scams", "title": "Did AVIS Rent-a-Car try to pull a scam?", "score": 14, "comments": 22, "sentiment": "negative", "date": "2025-01-29T16:30:00Z",
             "top_comments": ["I've felt pressured into paying extra for unnecessary coverage.", "This kind of thing happens all too often."]},
            {"id": "t14", "subreddit": "r/Scams", "title": "Dubai car rental scams.", "score": 10, "comments": 14, "sentiment": "negative", "date": "2025-01-28T12:00:00Z",
             "top_comments": ["Always verify the reputation of rental companies in Dubai.", "Some companies really exploit tourists."]},
            {"id": "t15", "subreddit": "r/Scams", "title": "Is this Italy traffic fine scam from Avis Rental Car?", "score": 12, "comments": 18, "sentiment": "negative", "date": "2025-01-27T10:00:00Z",
             "top_comments": ["I've faced something similar; be wary of these fines!", "Usually, it's a tactic to pull in money."]},
            {"id": "t16", "subreddit": "r/Scams", "title": "Miami Car Rental Scam", "score": 9, "comments": 11, "sentiment": "negative", "date": "2025-01-26T14:30:00Z",
             "top_comments": ["I noticed some shady dealings at the rental counters.", "Always read reviews before renting in Miami."]},
            {"id": "t17", "subreddit": "r/Scams", "title": "Warning: www.rentcars.com is a SCAM", "score": 16, "comments": 24, "sentiment": "negative", "date": "2025-01-25T09:00:00Z",
             "top_comments": ["I tried booking through them and had to deal with extra charges.", "It's not worth the hassle, stick to reputable sites."]},
            # r/cars
            {"id": "t18", "subreddit": "r/cars", "title": "Avis Car Rental: What is similar to a Mustang?", "score": 10, "comments": 15, "sentiment": "neutral", "date": "2025-01-24T13:45:00Z",
             "top_comments": ["You should check out the Camaro.", "The muscle car options are lacking at Avis."]},
            {"id": "t19", "subreddit": "r/cars", "title": "As a car guy, I get infuriated with the crappy cars Avis gives me when I go on work travel.", "score": 20, "comments": 30, "sentiment": "negative", "date": "2025-01-23T09:30:00Z",
             "top_comments": ["I had a similar experience with a poorly maintained vehicle.", "Always inspect the car before you drive off!"]},
            {"id": "t20", "subreddit": "r/cars", "title": "This is why you get the damage waiver on your rental car.", "score": 15, "comments": 10, "sentiment": "neutral", "date": "2025-01-22T15:15:00Z",
             "top_comments": ["I learned that lesson the hard way, unfortunately.", "They charge you for anything and everything."]},
            {"id": "t21", "subreddit": "r/cars", "title": "Which Rental Car Was Either Much Better or Much Worse than You Expected?", "score": 12, "comments": 20, "sentiment": "neutral", "date": "2025-01-21T11:00:00Z",
             "top_comments": ["I underestimated the Jeep rental, it was great!", "Avis can really surprise you for the worse."]},
            {"id": "t22", "subreddit": "r/cars", "title": "Anyone else notice, rental car companies are keeping cars longer?", "score": 10, "comments": 10, "sentiment": "neutral", "date": "2025-01-20T14:20:00Z",
             "top_comments": ["I've seen companies cycling through older models more.", "Quality seems to be declining across the board."]},
            # r/IAmA
            {"id": "t23", "subreddit": "r/IAmA", "title": "IamA Rental Car Agent for Avis-Budget Group. AMA!", "score": 25, "comments": 50, "sentiment": "neutral", "date": "2025-01-19T12:00:00Z",
             "top_comments": ["What do you think of the current policies around charges?", "How do you handle the customer complaints?"]},
            {"id": "t24", "subreddit": "r/IAmA", "title": "I own and manage an AVIS/BUDGET Car and Truck Rental store for the last 3 years! Ask Me Anything!", "score": 18, "comments": 30, "sentiment": "neutral", "date": "2025-01-18T10:30:00Z",
             "top_comments": ["What's the craziest issue you've ever seen with a renter?", "How do you manage the damage disputes?"]},
            {"id": "t25", "subreddit": "r/IAmA", "title": "IamA former Rental Car Agent, your worst travel nightmare, in the industry for 10 years AMA!", "score": 30, "comments": 40, "sentiment": "neutral", "date": "2025-01-17T14:00:00Z",
             "top_comments": ["What's the worst thing a customer has done?", "Do you have stories of people trying to cheat the system?"]},
            {"id": "t26", "subreddit": "r/IAmA", "title": "AMA Request: An Avis Car rental 'Independent Operator.'", "score": 5, "comments": 10, "sentiment": "neutral", "date": "2025-01-16T09:15:00Z",
             "top_comments": ["What are the differences in experiences as an independent operator?", "Do you face struggles we wouldn't know about?"]},
            {"id": "t27", "subreddit": "r/IAmA", "title": "IamA Rental Car Agent (AKA the guy who tells you want you don't want to hear) AMA!", "score": 15, "comments": 20, "sentiment": "neutral", "date": "2025-01-15T11:30:00Z",
             "top_comments": ["What's your script when people argue about extra fees?", "How often are complaints valid?"]},
            # r/unitedairlines
            {"id": "t28", "subreddit": "r/unitedairlines", "title": "$180 upcharge renting car through United vs. Avis directly?", "score": 22, "comments": 30, "sentiment": "negative", "date": "2025-01-14T14:45:00Z",
             "top_comments": ["It seems to be a common practice, sadly.", "I might stick with booking directly now."]},
            {"id": "t29", "subreddit": "r/unitedairlines", "title": "Anyone use the United portal to book an Avis rental car?", "score": 12, "comments": 18, "sentiment": "neutral", "date": "2025-01-13T10:00:00Z",
             "top_comments": ["Not worth it, I always have bad luck with it.", "It's a hit or miss!"]},
            {"id": "t30", "subreddit": "r/unitedairlines", "title": "Avis vs. Budget", "score": 16, "comments": 22, "sentiment": "neutral", "date": "2025-01-12T13:30:00Z",
             "top_comments": ["I've noticed Budget has better customer service lately.", "Both have their strengths and weaknesses."]},
            {"id": "t31", "subreddit": "r/unitedairlines", "title": "Booking Rental Car through United", "score": 10, "comments": 15, "sentiment": "neutral", "date": "2025-01-11T09:45:00Z",
             "top_comments": ["Make sure you check all fees before confirming.", "United partners with Avis often, which can be useful."]},
            {"id": "t32", "subreddit": "r/unitedairlines", "title": "PQP with Avis?", "score": 8, "comments": 10, "sentiment": "neutral", "date": "2025-01-10T15:00:00Z",
             "top_comments": ["Does it work well? I've heard mixed opinions.", "It's decent, but don't expect too much."]},
        ]
    },
    "hertz": {
        "posts": [
            {"id": "h1", "subreddit": "r/travel", "title": "Hertz rental experience at LAX", "score": 18, "comments": 22, "sentiment": "positive", "date": "2025-02-10T11:00:00Z",
             "top_comments": ["Great experience overall!", "The Gold Plus line saved me so much time."]},
            {"id": "h2", "subreddit": "r/cars", "title": "Hertz vs Enterprise for luxury rentals", "score": 14, "comments": 18, "sentiment": "neutral", "date": "2025-02-08T09:30:00Z",
             "top_comments": ["Hertz Dream Cars is worth checking out.", "Enterprise has better availability in my area."]},
            {"id": "h3", "subreddit": "r/TravelHacks", "title": "Hertz Gold Plus rewards - worth it?", "score": 20, "comments": 25, "sentiment": "positive", "date": "2025-02-06T14:15:00Z",
             "top_comments": ["Absolutely worth it for frequent renters.", "The skip-the-counter feature is a game changer."]},
            {"id": "h4", "subreddit": "r/Scams", "title": "Hertz charged me for damage I didn't cause", "score": 30, "comments": 45, "sentiment": "negative", "date": "2025-02-04T10:00:00Z",
             "top_comments": ["Document everything with photos and video!", "This happened to me too, had to dispute with my credit card."]},
            {"id": "h5", "subreddit": "r/cars", "title": "Hertz Dream Cars collection review", "score": 25, "comments": 20, "sentiment": "positive", "date": "2025-02-02T16:30:00Z",
             "top_comments": ["Rented a Corvette, totally worth it!", "Prices are steep but the experience is amazing."]},
        ]
    }
}
